server:
  port: 8889
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/oauth2_test?useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id:
#            client-secret:
#            redirect-uri:
#            scope:
#              - email
#              - profile
#          facebook:
#            client-id:
#            client-secret:
#            redirect-uri:
#            scope:
#              - email
#              - public_profile
#          github:
#            client-id:
#            client-secret:
#            redirect-uri:
#            scope:
#              - user:email
#              - read:user
#        provider:
#          facebook:
#            authorization-uri:
#            token-uri:
#            user-info-uri:
app:
  security:
    jwt-secret: phuongchu12313123131332131321321321313131312313
    jwt-expiration: 10800000 #1000*60*60*3
    jwt-refresh-token-expiration: 43200000 #1000*60*60*12
    jwt-cookie-name: phuongchu
cor:
  allow-origin: http://localhost:8080, https://localhost:8088
  allow-method: POST, GET, PUT, DELETE
  allow-credentials: true
